plugins:
  - jekyll-relative-links
  - jekyll-remote-theme # add this line to the plugins list if you already
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: pages-themes/cayman@v0.2.0
